import {useEffect,useState} from 'react'
import './admin-cms.css'
const empty={kind:'page',slug:'/new-page',locale:'both',status:'draft',title_fr:'',title_en:'',excerpt_fr:'',excerpt_en:'',body_fr:'',body_en:'',category:'',tags:[],featured:false,featured_image:'',author:'EVES',seo_title_fr:'',seo_title_en:'',seo_description_fr:'',seo_description_en:'',seo_keywords:[],canonical_url:'',metadata:{}}
const nav=[['dashboard','Tableau de bord','Dashboard','fa-chart-pie'],['pages','Pages du site','Website pages','fa-file-lines'],['news','Newsroom','Newsroom','fa-newspaper'],['media','Médiathèque','Media library','fa-images'],['settings','Réglages','Settings','fa-gear']]
const T=({lang,fr,en})=>lang==='fr'?fr:en
const I=({n})=><i className={`fa-solid ${n}`} aria-hidden="true"/>
const cp=x=>JSON.parse(JSON.stringify(x))
export default function Admin(){
 const [lang,setLang]=useState(()=>navigator.language?.toLowerCase().startsWith('fr')?'fr':'en'),[section,setSection]=useState('dashboard'),[data,setData]=useState({content:[],config:null}),[edit,setEdit]=useState(null),[q,setQ]=useState(''),[toast,setToast]=useState(''),[loading,setLoading]=useState(true),[mobile,setMobile]=useState(false)
 async function load(){setLoading(true);try{const r=await fetch('/api/cms',{credentials:'include',cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error);setData(j)}catch(e){setToast(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const all=data.content||[],pages=all.filter(x=>x.kind==='page'),news=all.filter(x=>x.kind==='news'),media=all.filter(x=>x.kind==='media')
 const items=(section==='pages'?pages:section==='news'?news:all).filter(x=>!q||`${x.title_fr} ${x.title_en} ${x.slug} ${x.category}`.toLowerCase().includes(q.toLowerCase()))
 async function saveContent(content){try{const r=await fetch('/api/cms',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});const j=await r.json();if(!r.ok)throw Error(j.error);setEdit(null);setToast(lang==='fr'?'Contenu enregistré.':'Content saved.');await load()}catch(e){setToast(e.message)}}
 async function deleteContent(id){if(!confirm(lang==='fr'?'Supprimer définitivement ?':'Delete permanently?'))return;try{const r=await fetch(`/api/cms?id=${encodeURIComponent(id)}`,{method:'DELETE',credentials:'include'});const j=await r.json();if(!r.ok)throw Error(j.error);await load()}catch(e){setToast(e.message)}}
 function create(kind){setEdit({...cp(empty),kind,slug:kind==='news'?`/news/new-story-${Date.now()}`:'/new-page',category:kind==='news'?'Actualités':''})}
 return <div className="eves-cms"><aside className={`cms-sidebar ${mobile?'open':''}`}><div className="cms-admin-brand"><img src={data.config?.logo_url||'/WhatsApp%20Image%202026-09-12%20at%203.24.08%20PM.jpeg'} alt="EVES"/><div><b>EVES CMS</b><small>Management Console</small></div><button onClick={()=>setMobile(false)}><I n="fa-xmark"/></button></div><nav>{nav.map(([k,fr,en,ic])=><button key={k} className={section===k?'active':''} onClick={()=>{setSection(k);setEdit(null);setMobile(false)}}><I n={ic}/><span><T lang={lang} fr={fr} en={en}/></span></button>)}</nav><a className="view-site" href="/" target="_blank" rel="noreferrer"><I n="fa-arrow-up-right-from-square"/> <T lang={lang} fr="Voir le site" en="View website"/></a></aside>{mobile&&<div className="cms-mask" onClick={()=>setMobile(false)}/>}<main className="cms-main"><header className="cms-toolbar"><button className="cms-hamb" onClick={()=>setMobile(true)}><I n="fa-bars"/></button><div className="cms-search"><I n="fa-magnifying-glass"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher…"/></div><button className="cms-lang" onClick={()=>setLang(lang==='fr'?'en':'fr')}><I n="fa-language"/> {lang.toUpperCase()}</button><a className="cms-live" href="/" target="_blank" rel="noreferrer"><I n="fa-globe"/> Live</a></header>{toast&&<div className="cms-toast" onClick={()=>setToast('')}><I n="fa-circle-check"/> {toast}</div>}{loading?<div className="cms-loading"><I n="fa-spinner"/> Loading…</div>:edit?<Editor initial={edit} close={()=>setEdit(null)} save={saveContent}/>:section==='dashboard'?<Dashboard data={data} lang={lang} setSection={setSection} create={create}/>:section==='settings'?<Settings config={data.config||{}} save={async config=>{try{const r=await fetch('/api/cms',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'config',config})});const j=await r.json();if(!r.ok)throw Error(j.error);setToast('Settings saved');load()}catch(e){setToast(e.message)}}} lang={lang}/>:section==='media'?<Media items={media}/>:<List items={items} isNews={section==='news'} lang={lang} create={()=>create(section==='news'?'news':'page')} edit={setEdit} remove={deleteContent}/>}</main></div>
}
function Dashboard({data,lang,setSection,create}){const a=data.content||[];return <div className="cms-page"><div className="cms-title"><div><span>EVES CMS</span><h1><T lang={lang} fr="Tableau de bord" en="Dashboard"/></h1><p><T lang={lang} fr="Une source de vérité pour le site public et la newsroom." en="One source of truth for the public website and newsroom."/></p></div><button className="cms-primary" onClick={()=>create('news')}><I n="fa-plus"/> <T lang={lang} fr="Nouvelle actualité" en="New story"/></button></div><div className="cms-stats"><Stat icon="fa-file-lines" n={a.filter(x=>x.kind==='page').length} t="Pages"/><Stat icon="fa-newspaper" n={a.filter(x=>x.kind==='news').length} t="Newsroom"/><Stat icon="fa-circle-check" n={a.filter(x=>x.status==='published').length} t="Published"/><Stat icon="fa-pen-to-square" n={a.filter(x=>x.status!=='published').length} t="Drafts"/></div><section className="cms-panel"><h2><T lang={lang} fr="Publication en temps réel" en="Realtime publishing"/></h2><p><T lang={lang} fr="Les pages, traductions, textes, images, SEO et actualités sont stockés dans Supabase. Après publication, le site public reçoit automatiquement la nouvelle version via Supabase Realtime." en="Pages, translations, copy, images, SEO and news are stored in Supabase. After publishing, the public website automatically receives the new version through Supabase Realtime."/></p><div className="quick-grid"><button onClick={()=>setSection('pages')}><I n="fa-file-lines"/> Pages</button><button onClick={()=>setSection('news')}><I n="fa-newspaper"/> Newsroom</button><button onClick={()=>setSection('media')}><I n="fa-images"/> Media</button><button onClick={()=>setSection('settings')}><I n="fa-sliders"/> Settings</button></div></section></div>}
function Stat({icon,n,t}){return <div><I n={icon}/><b>{n}</b><span>{t}</span></div>}
function List({items,isNews,lang,create,edit,remove}){return <div className="cms-page"><div className="cms-title"><div><span>{isNews?'NEWSROOM':'WEBSITE CONTENT'}</span><h1>{isNews?'Newsroom':lang==='fr'?'Pages du site':'Website pages'}</h1><p><T lang={lang} fr="Modifier, traduire, enregistrer et publier." en="Edit, translate, save and publish."/></p></div><button className="cms-primary" onClick={create}><I n="fa-plus"/> <T lang={lang} fr={isNews?'Nouvelle actualité':'Nouvelle page'} en={isNews?'New story':'New page'}/></button></div><section className="cms-panel"><div className="cms-list-head"><b>Titre / Title</b><b>URL</b><b>Statut</b><b>Actions</b></div>{items.map(x=><div className="cms-row" key={x.id}><div><strong>{x[`title_${lang}`]||x.title_fr||'Sans titre'}</strong><small>{isNews?`${x.category||'Actualités'} · ${x.author||'EVES'}`:'Page institutionnelle'}</small></div><code>{x.slug}</code><span className={`cms-status ${x.status}`}>{x.status}</span><div><button onClick={()=>edit(cp(x))}><I n="fa-pen"/></button><button onClick={()=>remove(x.id)}><I n="fa-trash"/></button></div></div>)}</section></div>}
function Editor({initial,close,save}){const [v,setV]=useState(cp(initial));const set=(k,val)=>setV(x=>({...x,[k]:val}));const field=(k,l)=><textarea value={v[`${k}_${l}`]||''} onChange={e=>set(`${k}_${l}`,e.target.value)}/>;return <div className="cms-page"><div className="cms-title"><div><span>{v.kind==='news'?'NEWSROOM EDITOR':'PAGE EDITOR'}</span><h1>{v.kind==='news'?'Éditer l’actualité':'Éditer la page'}</h1></div><div className="editor-actions"><button onClick={close}>Annuler</button><button className="cms-primary" onClick={()=>save({...v,published_at:v.status==='published'?(v.published_at||new Date().toISOString()):v.published_at})}><I n="fa-cloud-arrow-up"/> Enregistrer</button></div></div><section className="cms-panel editor"><div className="editor-grid"><div><h3>Français</h3><label>Titre{field('title','fr')}</label><label>Résumé{field('excerpt','fr')}</label><label>Contenu{field('body','fr')}</label></div><div><h3>English</h3><label>Title{field('title','en')}</label><label>Excerpt{field('excerpt','en')}</label><label>Body{field('body','en')}</label></div></div><div className="editor-fields"><label>URL / Slug<input value={v.slug} onChange={e=>set('slug',e.target.value)}/></label><label>Category<input value={v.category||''} onChange={e=>set('category',e.target.value)}/></label><label>Author<input value={v.author||''} onChange={e=>set('author',e.target.value)}/></label><label>Status<select value={v.status} onChange={e=>set('status',e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="scheduled">Scheduled</option><option value="archived">Archived</option></select></label><label>Featured image URL<input value={v.featured_image||''} onChange={e=>set('featured_image',e.target.value)}/></label><label>Tags<input value={(v.tags||[]).join(', ')} onChange={e=>set('tags',e.target.value.split(',').map(s=>s.trim()).filter(Boolean))}/></label></div><details><summary>SEO</summary><div className="editor-grid"><div><label>SEO title FR{field('seo_title','fr')}</label><label>SEO description FR{field('seo_description','fr')}</label></div><div><label>SEO title EN{field('seo_title','en')}</label><label>SEO description EN{field('seo_description','en')}</label></div></div></details></section></div>}
function Media({items}){return <div className="cms-page"><div className="cms-title"><div><span>MEDIA LIBRARY</span><h1>Médiathèque</h1></div></div><section className="media-grid">{items.map(x=><div className="media-card" key={x.id}>{x.featured_image?<img src={x.featured_image} alt=""/>:<I n="fa-image"/>}<b>{x.title_fr||x.slug}</b><small>{x.featured_image||x.slug}</small></div>)}</section></div>}
function Settings({config,lang,save}){const [v,setV]=useState({...config});return <div className="cms-page"><div className="cms-title"><div><span>GLOBAL SETTINGS</span><h1><T lang={lang} fr="Réglages du site" en="Site settings"/></h1></div><button className="cms-primary" onClick={()=>save(v)}><I n="fa-floppy-disk"/> Save</button></div><section className="cms-panel settings-grid">{[['site_name','Nom du site','Site name'],['contact_email','Email','Email'],['phone','Téléphone','Phone'],['logo_url','Logo URL','Logo URL'],['facebook','Facebook','Facebook'],['linkedin','LinkedIn','LinkedIn'],['instagram','Instagram','Instagram'],['whatsapp','WhatsApp','WhatsApp']].map(([k,fr,en])=><label key={k}><T lang={lang} fr={fr} en={en}/><input value={v[k]||''} onChange={e=>setV({...v,[k]:e.target.value})}/></label>)}</section></div>}
