import {useEffect,useState} from 'react'
const photos=[
{src:'https://upload.wikimedia.org/wikipedia/commons/e/e3/Primary_school_life_in_cameroon.jpg',alt:'Écoliers camerounais jouant devant leur école primaire',cap:'Éducation et épanouissement des enfants au Cameroun.',credit:'Vitalis Barosse · CC BY-SA 4.0'},
{src:'https://upload.wikimedia.org/wikipedia/commons/c/c8/Tinto_school_children.jpg',alt:'Enfants camerounais participant à une activité culturelle à Tinto',cap:'Jeunesse, culture et vie communautaire.',credit:'Garviston · CC BY-SA 4.0'},
{src:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Hand_Hygiene_becomes_an_Imperative_for_kids_in_rural_Cameroon.jpg/1280px-Hand_Hygiene_becomes_an_Imperative_for_kids_in_rural_Cameroon.jpg',alt:'Garçons se lavant les mains dans une communauté rurale du Cameroun',cap:'Santé, prévention et dignité au quotidien.',credit:'Awachirac · CC BY-SA 4.0'},
{src:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Vaccination_team_at_a_health_center_%2834601931781%29.jpg/1280px-Vaccination_team_at_a_health_center_%2834601931781%29.jpg',alt:'Équipe de vaccination dans un centre de santé au Cameroun',cap:'Mobilisation communautaire pour la santé des enfants.',credit:'CDC Global · CC BY 2.0'},
{src:'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1800&q=88',alt:'Enfants réunis autour d’une activité éducative',cap:'Apprendre ensemble, construire les possibilités de demain.',credit:'Image illustrative'}]
const axes=[['fa-solid fa-book-open','Éducation','Favoriser l’accès, le maintien et la réinsertion scolaire des enfants et jeunes vulnérables.'],['fa-solid fa-shield-heart','Protection & autonomisation','Prévenir les violences, renforcer la protection et créer des parcours d’autonomie.'],['fa-solid fa-heart-pulse','Santé','Promouvoir le bien-être, la prévention et l’accès aux ressources sanitaires.'],['fa-solid fa-seedling','Résilience climatique','Soutenir les pratiques durables, la sensibilisation environnementale et l’adaptation.'],['fa-solid fa-bullhorn','Mobilisation & plaidoyer','Fédérer les acteurs, documenter les expériences et porter les voix des communautés.']]
const projects=[['01','Éducation & réinsertion','Accompagnement éducatif et réinsertion des enfants et jeunes vulnérables avec les relais locaux.'],['02','Protection de l’enfance et jeunesse','Prévention, orientation, accompagnement psychosocial et renforcement des mécanismes communautaires.'],['03','Initiatives santé communautaire','Mobilisation des acteurs sociaux et solidaires autour de la santé, de la prévention et du bien-être.'],['04','Résilience & économie sociale et solidaire','Appui aux OESS comme leviers de développement durable, de solidarité et d’autonomisation.'],['05','Recherche, innovation & plaidoyer','Recherche-action, capitalisation, mentorat et mobilisation pour des réponses plus inclusives.']]
const zones=['Nord-Ouest','Extrême-Nord','Nord','Adamaoua','Est','Ouest','Noun']
const news=[['Actualité institutionnelle','EVES est officiellement reconnue','27 août 2026','Récépissé de déclaration préfectorale n°001444/RDA/JO6/SAAJP/BAPP, Préfecture du Mfoundi.'],['Réseau','Une communauté d’action au service du terrain','2026','Membres, référents régionaux, partenaires et associations relais coordonnent les actions et opportunités.'],['ESS','Les OESS au cœur de notre approche','2026','EVES valorise les organisations de l’économie sociale et solidaire comme leviers de développement durable.']]
const events=[['2026','Lancement et structuration du réseau','Présentation d’EVES, de ses cinq axes, de son réseau et de ses zones prioritaires.'],['2027','Déploiement pilote','Mise en œuvre progressive des programmes avec les associations relais et partenaires.'],['2028–2029','Capitalisation & expansion','Documentation des résultats, consolidation des partenariats et extension selon les besoins.']]
const Icon=({n})=><i className={n} aria-hidden="true"/>
const Title=({e,t,p,light})=><div className={'section-title '+(light?'light':'')}><span className="eyebrow">{e}</span><h2 dangerouslySetInnerHTML={{__html:t}}/>{p&&<p>{p}</p>}</div>
function App(){
 const [menu,setMenu]=useState(false),[slide,setSlide]=useState(0)
 useEffect(()=>{const t=setInterval(()=>setSlide(v=>(v+1)%photos.length),5500);return()=>clearInterval(t)},[])
 const go=id=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}
 const nav=[['about','À propos'],['causes','Causes'],['projects','Projets'],['impact','Impact'],['team','Équipe'],['partners','Partenaires'],['resources','Ressources'],['news','Actualités'],['events','Événements'],['volunteer','Bénévolat'],['donate','Soutenir'],['contact','Contact']]
 return <div className="site">
  <div className="topbar"><div className="container topbar-inner"><span><Icon n="fa-solid fa-location-dot"/> Cameroun · Une action ouverte à toutes et tous</span><span className="toplinks"><a href="mailto:contact@eves.cm"><Icon n="fa-solid fa-envelope"/> contact@eves.cm</a><a href="tel:+237656987759"><Icon n="fa-solid fa-phone"/> +237 656 987 759</a></span></div></div>
  <header className="header"><div className="container header-inner"><button className="brand" onClick={()=>go('home')} aria-label="Accueil EVES"><img src="/logo.svg" alt="Logo officiel EVES"/></button><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Menu"><Icon n={menu?'fa-solid fa-xmark':'fa-solid fa-bars'}/></button><nav className={menu?'open':''}><a href="#home" onClick={()=>go('home')}>Accueil</a>{nav.map(([id,l])=><a key={id} href={'#'+id} onClick={()=>go(id)}>{l}</a>)}<a className="nav-donate" href="#donate" onClick={()=>go('donate')}><Icon n="fa-solid fa-hand-holding-heart"/> Soutenir</a></nav></div></header>
  <main>
   <section id="home" className="hero"><div className="hero-slides">{photos.map((p,i)=><img key={p.src} className={i===slide?'active':''} src={p.src} alt={p.alt}/>)}</div><div className="hero-overlay"/><div className="container hero-inner"><div className="hero-copy"><span className="eyebrow gold">ÉDUCATION · PROTECTION · ÉMANCIPATION</span><h1>Ensemble,<br/>construisons un avenir <span>plus inclusif.</span></h1><p>EVES accompagne les enfants, les jeunes et leurs familles les plus vulnérables sur les plans éducatif, social, sanitaire et environnemental, en s’appuyant sur les organisations de l’économie sociale et solidaire.</p><div className="actions"><a className="btn primary" href="#causes">Découvrir nos actions <Icon n="fa-solid fa-arrow-right"/></a><a className="btn ghost" href="#about">Qui sommes-nous ?</a></div></div><div className="recognition-stamp"><Icon n="fa-solid fa-certificate"/><div><b>RECONNUE OFFICIELLEMENT</b><strong>Récépissé n°001444/RDA/JO6/SAAJP/BAPP</strong><small>27 août 2026 · Préfecture du Mfoundi</small></div></div><div className="slider-controls"><button onClick={()=>setSlide((slide-1+photos.length)%photos.length)} aria-label="Précédente"><Icon n="fa-solid fa-arrow-left"/></button><span>{String(slide+1).padStart(2,'0')} / {String(photos.length).padStart(2,'0')}</span><button onClick={()=>setSlide((slide+1)%photos.length)} aria-label="Suivante"><Icon n="fa-solid fa-arrow-right"/></button></div></div></section>
   <section className="quick-links"><div className="container quick-grid"><div className="quick-intro"><span className="eyebrow">NOTRE ENGAGEMENT</span><h2>Des actions pensées <span>avec les communautés.</span></h2><p>Nous partons des réalités locales, des forces existantes et des solidarités qui permettent aux familles et aux jeunes d’avancer.</p></div><a href="#donate"><Icon n="fa-solid fa-hand-holding-heart"/><b>Soutenir EVES</b><small>Contribuer à nos actions</small></a><a href="#partners"><Icon n="fa-solid fa-people-group"/><b>Devenir partenaire</b><small>Construire avec nous</small></a><a href="#volunteer"><Icon n="fa-solid fa-hands-helping"/><b>Être bénévole</b><small>Donner de son temps</small></a></div></section>
   <section id="about" className="section about"><div className="container two-col"><div><Title e="À PROPOS D’EVES" t="Une société où chaque enfant peut <span>réaliser son potentiel.</span>" p="Notre mission est de contribuer à un environnement où l’éducation, la protection, la santé, la solidarité et l’autonomisation deviennent des leviers réels pour les personnes vulnérables."/><p>EVES — <strong>Éducation aux Vulnérabilités de l’Enfance et de la Jeunesse, par l’Économie Sociale et Solidaire</strong> — agit avec les enfants, les jeunes et leurs familles les plus vulnérables.</p><p>Notre ciblage est ouvert à toutes et tous, sans distinction de religion, d’origine ou de statut. Les OESS constituent un levier central de notre démarche.</p><div className="official"><Icon n="fa-solid fa-shield-halved"/><div><b>Reconnaissance officielle</b><span>Récépissé de déclaration préfectorale n°001444/RDA/JO6/SAAJP/BAPP du 27 août 2026 — Préfecture du Mfoundi.</span></div></div></div><figure className="editorial-photo"><img src={photos[0].src} alt={photos[0].alt}/><figcaption><b>Grandir. Apprendre. Participer.</b><span>{photos[0].cap}</span></figcaption></figure></div></section>
   <section className="photo-strip"><div className="container"><div className="strip-head"><div><span className="eyebrow">EN IMAGES</span><h2>Des réalités locales, <span>des possibilités.</span></h2></div><p>Une présence qui relie éducation, santé, protection et mobilisation communautaire.</p></div><div className="strip-grid">{photos.slice(1).map(p=><figure key={p.src}><img src={p.src} alt={p.alt}/><figcaption>{p.cap}<small>{p.credit}</small></figcaption></figure>)}</div></div></section>
   <section id="causes" className="section causes"><div className="container"><Title e="NOS 5 AXES" t="Les causes qui <span>nous mobilisent.</span>" p="Cinq axes structurent l’action d’EVES et relient les besoins du terrain à la mobilisation, au partenariat et au plaidoyer."/><div className="axis-grid">{axes.map(([ic,t,d],i)=><article key={t}><span className="axis-number">0{i+1}</span><div className="axis-icon"><Icon n={ic}/></div><h3>{t}</h3><p>{d}</p><a href="#projects">Voir les actions <Icon n="fa-solid fa-arrow-right"/></a></article>)}</div></div></section>
   <section id="projects" className="section projects"><div className="container"><Title e="NOS PROGRAMMES" t="Des programmes conçus pour <span>agir concrètement.</span>"/><div className="project-list">{projects.map(([n,t,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><Icon n="fa-solid fa-arrow-up-right-from-square"/></article>)}</div></div></section>
   <section id="impact" className="impact"><div className="container"><Title e="IMPACT & RESPONSABILITÉ" t="Mesurer les progrès. <span>Rendre compte.</span>" light/><div className="impact-grid">{[['400+','enfants & jeunes','Objectif d’accompagnement éducatif et de réinsertion.'],['1 500','familles','Ciblées par les actions de sensibilisation et de proximité.'],['15','associations relais','À renforcer et mobiliser autour des territoires.'],['7','zones prioritaires','Avec une ouverture au territoire national et à l’international.']].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span><p>{x[2]}</p></div>)}</div><p className="impact-note">Les indicateurs constituent des ambitions de développement et évolueront avec les projets effectivement financés et déployés.</p></div></section>
   <section id="team" className="section team"><div className="container"><Title e="NOTRE ÉQUIPE & GOUVERNANCE" t="Une organisation qui relie <span>terrain et stratégie.</span>" p="La gouvernance d’EVES vise notamment à promouvoir les OESS dans les secteurs social, éducatif, sanitaire, culturel, agricole et financier."/><div className="team-grid">{[['fa-solid fa-compass-drafting','Direction & coordination','Pilotage stratégique, coordination des programmes et relations institutionnelles.'],['fa-solid fa-map-location-dot','Référents régionaux','Relais territoriaux et coordination des actions avec les associations locales.'],['fa-solid fa-people-roof','Réseau des OESS','Associations et organisations de l’économie sociale et solidaire comme leviers de développement.']].map(x=><article key={x[1]}><Icon n={x[0]}/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
   <section id="partners" className="section partners"><div className="container partner-box"><div><span className="eyebrow">PARTENARIATS</span><h2>Construisons des <span>solutions durables.</span></h2><p>EVES est ouverte aux collaborations avec associations, institutions, collectivités, universités, entreprises, bailleurs, fondations et acteurs de l’ESS.</p></div><a className="btn primary" href="mailto:contact@eves.cm?subject=Partenariat%20EVES">Proposer un partenariat <Icon n="fa-solid fa-arrow-right"/></a></div></section>
   <section id="resources" className="section resources"><div className="container"><Title e="RESSOURCES & RAPPORTS" t="Comprendre, documenter et <span>partager.</span>"/><div className="resource-grid">{[['fa-solid fa-file-lines','Rapports & publications','Rapports d’activités, études, notes et documents de capitalisation.'],['fa-solid fa-book-open-reader','Bibliothèque EVES','Ressources sur l’éducation, la protection, la santé, le climat et l’ESS.'],['fa-solid fa-location-crosshairs','Zones d’intervention',zones.join(' · ') ]].map(x=><article key={x[1]}><Icon n={x[0]}/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
   <section id="news" className="section news"><div className="container"><Title e="ACTUALITÉS & BLOG" t="Les nouvelles de <span>notre réseau.</span>"/><div className="news-grid">{news.map(x=><article key={x[1]}><span className="tag">{x[0]}</span><small>{x[2]}</small><h3>{x[1]}</h3><p>{x[3]}</p><a href="#contact">Lire l’article <Icon n="fa-solid fa-arrow-right"/></a></article>)}</div></div></section>
   <section id="events" className="section events"><div className="container"><Title e="ÉVÉNEMENTS" t="Agir ensemble, <span>sur le terrain.</span>"/><div className="event-list">{events.map(x=><article key={x[0]}><Icon n="fa-regular fa-calendar-days"/><strong>{x[0]}</strong><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></div></section>
   <section id="volunteer" className="volunteer"><div className="container volunteer-box"><div><span className="eyebrow gold">DEVENIR BÉNÉVOLE</span><h2>Votre temps peut devenir <span>une force.</span></h2><p>Participez aux actions communautaires, à la communication, à la recherche, aux événements ou à la mobilisation du réseau.</p></div><a className="btn light-btn" href="mailto:contact@eves.cm?subject=Volontariat%20EVES">Je veux m’engager <Icon n="fa-solid fa-arrow-right"/></a></div></section>
   <section id="donate" className="section donate"><div className="container donate-box"><div><span className="eyebrow">SOUTENIR EVES</span><h2>Chaque contribution peut <span>ouvrir une possibilité.</span></h2><p>Votre soutien aide à préparer et déployer des actions adaptées aux réalités des enfants, des jeunes, des familles et des communautés.</p></div><div className="donate-actions"><a className="btn primary" href="mailto:contact@eves.cm?subject=Soutien%20EVES"><Icon n="fa-solid fa-heart"/> Soutenir le programme</a><a className="btn outline-dark" href="#contact">Nous contacter</a></div></div></section>
   <section className="newsletter"><div className="container newsletter-box"><div><span className="eyebrow">NEWSLETTER EVES</span><h2>Recevez les nouvelles <span>du réseau.</span></h2><p>Actualités, appels à collaboration, événements et informations sur nos actions.</p></div><form onSubmit={e=>e.preventDefault()}><label htmlFor="email">Votre adresse email</label><div><input id="email" type="email" placeholder="vous@exemple.com" required/><button className="btn primary">S’abonner <Icon n="fa-solid fa-paper-plane"/></button></div><small>En vous inscrivant, vous acceptez de recevoir les communications d’EVES.</small></form></div></section>
   <section id="contact" className="section contact"><div className="container contact-grid"><div><Title e="CONTACT" t="Parlons de ce que nous pouvons <span>construire ensemble.</span>"/><p>Pour un partenariat, une proposition de projet, une demande d’information, une implication bénévole ou une collaboration avec une OESS, contactez EVES.</p><div className="contact-links"><a href="mailto:contact@eves.cm"><Icon n="fa-solid fa-envelope"/> contact@eves.cm</a><a href="tel:+237656987759"><Icon n="fa-solid fa-phone"/> +237 656 987 759</a><a href="#home"><Icon n="fa-solid fa-globe"/> Cameroun · National · International selon les besoins</a></div></div><div className="contact-card"><img src="/logo.svg" alt="Logo officiel EVES"/><b>Éducation · Protection · Émancipation</b><span>Association camerounaise engagée auprès des enfants, des jeunes et des familles vulnérables.</span><div className="zones">{zones.map(z=><span key={z}>{z}</span>)}</div></div></div></section>
  </main>
  <footer><div className="container footer-grid"><div><img className="footer-logo" src="/logo.svg" alt="Logo EVES"/><p>EVES agit pour l’éducation, la protection, la santé, la résilience climatique et la mobilisation, en s’appuyant sur l’économie sociale et solidaire.</p></div><div><b>Navigation</b><a href="#about">À propos</a><a href="#causes">Nos causes</a><a href="#projects">Projets</a><a href="#news">Actualités</a><a href="#contact">Contact</a></div><div><b>Nous rejoindre</b><a href="#volunteer">Bénévolat</a><a href="#partners">Partenariat</a><a href="#donate">Soutenir EVES</a><a href="#resources">Ressources</a></div></div><div className="container footer-bottom"><span>© 2026 EVES — Tous droits réservés.</span><span>Développé par <b>MTECHsolutions</b> · +237 656 987 759</span></div></footer>
 </div>
}
export default App
