import {useEffect,useState} from 'react'

const photos=[
{src:'https://upload.wikimedia.org/wikipedia/commons/e/e3/Primary_school_life_in_cameroon.jpg',alt:'Écoliers camerounais jouant devant leur école primaire',cap:'Éducation et épanouissement des enfants au Cameroun.',credit:'Vitalis Barosse · CC BY-SA 4.0'},
{src:'https://upload.wikimedia.org/wikipedia/commons/c/c8/Tinto_school_children.jpg',alt:'Enfants camerounais participant à une activité culturelle à Tinto',cap:'Jeunesse, culture et vie communautaire.',credit:'Garviston · CC BY-SA 4.0'},
{src:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Hand_Hygiene_becomes_an_Imperative_for_kids_in_rural_Cameroon.jpg/1280px-Hand_Hygiene_becomes_an_Imperative_for_kids_in_rural_Cameroon.jpg',alt:'Garçons se lavant les mains dans une communauté rurale du Cameroun',cap:'Santé, prévention et dignité au quotidien.',credit:'Awachirac · CC BY-SA 4.0'},
{src:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Vaccination_team_at_a_health_center_%2834601931781%29.jpg/1280px-Vaccination_team_at_a_health_center_%2834601931781%29.jpg',alt:'Équipe de vaccination dans un centre de santé au Cameroun',cap:'Mobilisation communautaire pour la santé des enfants.',credit:'CDC Global · CC BY 2.0'},
{src:'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1800&q=88',alt:'Enfants réunis autour d’une activité éducative',cap:'Apprendre ensemble, construire les possibilités de demain.',credit:'Image illustrative'}]

const axes=[
['fa-solid fa-book-open','OS1 · Scolarisation','Favoriser l’accès, le maintien et la réinsertion scolaire des enfants et jeunes vulnérables.'],
['fa-solid fa-seedling','OS2 · Résilience climatique','Renforcer la résilience, l’adaptation et les pratiques durables face aux vulnérabilités climatiques.'],
['fa-solid fa-shield-heart','OS3 · Protection & VBG','Prévenir les violences, renforcer la protection et soutenir l’autonomisation des enfants, jeunes et familles.'],
['fa-solid fa-handshake-angle','OS4 · Économie sociale et solidaire','Promouvoir les OESS comme leviers de développement durable dans les secteurs social, éducatif, sanitaire, culturel, agricole et financier.'],
['fa-solid fa-lightbulb','OS5 · Innovation & plaidoyer','Développer la recherche, l’innovation, le plaidoyer et les solutions adaptées aux réalités des communautés.']]

const projects=[
['01','Scolarisation & réinsertion','Accompagnement éducatif, maintien à l’école et réinsertion des enfants et jeunes vulnérables.'],
['02','Résilience climatique','Actions d’adaptation, sensibilisation environnementale et solutions locales pour les territoires exposés.'],
['03','Protection & prévention des VBG','Prévention, orientation, accompagnement et renforcement des mécanismes communautaires de protection.'],
['04','OESS & autonomisation','Appui aux organisations de l’économie sociale et solidaire et aux activités génératrices de revenus.'],
['05','Innovation, recherche & plaidoyer','Recherche-action, capitalisation, innovation, mentorat et mobilisation pour des réponses inclusives.']]

const zones=['Nord-Ouest','Extrême-Nord','Nord','Adamaoua','Est','Ouest','Noun']
const news=[
['Institutionnel','EVES est officiellement reconnue','27 août 2026','Récépissé de déclaration préfectorale n°001444/RDA/JO6/SAAJP/BAPP, Préfecture du Mfoundi.'],
['Gouvernance','Le Comité Consultatif renforce l’expertise EVES','Septembre 2026','Des profils complémentaires en investissement, santé, éducation, IA et climat accompagnent la stratégie de l’association.'],
['ESS','Les OESS au cœur de l’approche EVES','Septembre 2026','EVES place les organisations de l’économie sociale et solidaire au cœur des solutions de développement durable.']]
const events=[['2026','Lancement et structuration du réseau','Présentation d’EVES, de ses cinq objectifs spécifiques, de son réseau et de ses zones prioritaires.'],['Semaine du 14/09/2026','Lancement du site bilingue','Mise en ligne de la plateforme institutionnelle EVES en français et en anglais.'],['2027','Déploiement pilote','Mise en œuvre progressive des programmes avec les associations relais et partenaires.'],['2028–2029','Capitalisation & expansion','Documentation des résultats, consolidation des partenariats et extension selon les besoins.']]

const advisory=[
['fa-solid fa-globe','M. Chamas Awad','EuroGulf Consulting','Expert en relations EU-MENA/Afrique/Asie, Government Affairs & Investment Promotion. Membre du Comité Consultatif d’EVES.'],
['fa-solid fa-user-doctor','Dr Nesrin','Tripoli, Libye · EuroGulf Consulting','Médecin généraliste et pharmacienne clinique. Piste de collaboration sur le volet santé des projets EVES, avec des synergies possibles sur OS1 et OS3.'],
['fa-solid fa-graduation-cap','Mrs Katerina Makotsi','Éducation · Business · IA','Retour attendu sur OS1 et plusieurs pistes : plateforme des OESS, campagnes pour l’établissement des actes de naissance, causeries éducatives à destination des hommes et plateforme professionnelle de certifications courtes aux métiers AGR.'],
['fa-solid fa-cloud-sun','Pr Joseph Pascal Mbaha','Expertise universitaire · Climat','Professeur d’université, spécialiste des questions climatiques. Profil pressenti pour renforcer l’expertise du Comité Consultatif sur OS2 — résilience climatique et adaptation.']]

const donationResults=[
['fa-solid fa-house-chimney-medical','SAFEHOME / MAISON DES RÉSILIENCES','Création de lieux de refuge et de prise en charge des vulnérabilités, adossés aux cinq objectifs spécifiques.'],
['fa-solid fa-pills','Médicaments & équipements','Mobilisation de dons de médicaments et de matériels médicaux pour les populations et structures qui en ont besoin.'],
['fa-solid fa-stethoscope','Campagnes de santé','Organisation de campagnes de santé gratuites et d’actions de prévention communautaire.'],
['fa-solid fa-hospital','Hôpitaux & équipements','Construction ou soutien à des hôpitaux et appui par des dons d’équipements selon les besoins identifiés.'],
['fa-solid fa-droplet','Eau & puits','Offre de puits pour les zones sinistrées, underserved ou arides et amélioration de l’accès à l’eau.'],
['fa-solid fa-people-arrows','Renforcement des capacités','Développement des compétences des acteurs locaux et des organisations relais.'],
['fa-solid fa-book-open-reader','Programme Cours d’éducation aux Vulnérabilités','Développement de parcours éducatifs dédiés à la compréhension et à la réponse aux vulnérabilités.']]

const followups=[
'Cadrage du partenariat santé avec Dr Nesrin : périmètre, objectifs spécifiques concernés et forme d’engagement.',
'Suivi du retour de Katerina Makotsi sur OS1, la plateforme des OESS, les campagnes d’actes de naissance, les causeries pour les hommes et la plateforme de certifications AGR.',
'Suivi du calendrier des financements en cours, notamment RAJA Foundation et PISCCA.',
'Définition du montage opérationnel et financier du volet don/humanitaire : SAFEHOME / formulation à acter, santé et accès à l’eau.' ]

const governance=['Bureau Exécutif à 6 membres élus par l’Assemblée Générale','Innovation Lab — 2 co-coordonnateurs','Comité Consultatif','Comité scientifique','Comité de sauvegarde de l’enfant']
const Icon=({n})=><i className={n} aria-hidden="true"/>
const Title=({e,t,p,light})=><div className={'section-title '+(light?'light':'')}><span className="eyebrow">{e}</span><h2 dangerouslySetInnerHTML={{__html:t}}/>{p&&<p>{p}</p>}</div>

function App(){
 const [menu,setMenu]=useState(false),[slide,setSlide]=useState(0)
 useEffect(()=>{const t=setInterval(()=>setSlide(v=>(v+1)%photos.length),5500);return()=>clearInterval(t)},[])
 const go=id=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}
 const nav=[['about','À propos'],['causes','5 objectifs'],['projects','Programmes'],['impact','Impact'],['team','Gouvernance'],['advisory','Comité consultatif'],['partners','Partenaires'],['resources','Ressources'],['news','Actualités'],['events','Événements'],['volunteer','Bénévolat'],['donate','Soutenir'],['contact','Contact']]
 return <div className="site">
  <div className="topbar"><div className="container topbar-inner"><span><Icon n="fa-solid fa-location-dot"/> Cameroun · Action ouverte à toutes et tous</span><span className="toplinks"><a href="mailto:contact@eves.cm"><Icon n="fa-solid fa-envelope"/> contact@eves.cm</a><a href="tel:+237656987759"><Icon n="fa-solid fa-phone"/> +237 656 987 759</a></span></div></div>
  <header className="header"><div className="container header-inner"><button className="brand" onClick={()=>go('home')} aria-label="Accueil EVES"><img src="/logo.svg" alt="Logo officiel EVES — Éducation aux Vulnérabilités de l’Enfance et de la Jeunesse, par l’Économie Sociale et Solidaire"/></button><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Menu"><Icon n={menu?'fa-solid fa-xmark':'fa-solid fa-bars'}/></button><nav className={menu?'open':''}><a href="#home" onClick={()=>go('home')}>Accueil</a>{nav.map(([id,l])=><a key={id} href={'#'+id} onClick={()=>go(id)}>{l}</a>)}<a className="nav-donate" href="#donate" onClick={()=>go('donate')}><Icon n="fa-solid fa-hand-holding-heart"/> Soutenir</a></nav></div></header>
  <main>
   <section id="home" className="hero"><div className="hero-slides">{photos.map((p,i)=><img key={p.src} className={i===slide?'active':''} src={p.src} alt={p.alt}/>)}</div><div className="hero-overlay"/><div className="container hero-inner"><div className="hero-copy"><span className="eyebrow gold">ÉDUCATION · PROTECTION · ÉMANCIPATION</span><h1>Ensemble,<br/>construisons un avenir <span>plus inclusif.</span></h1><p>EVES accompagne les enfants, les jeunes et leurs familles les plus vulnérables sur les plans éducatif, social, sanitaire et environnemental, en s’appuyant sur les organisations de l’économie sociale et solidaire.</p><div className="actions"><a className="btn primary" href="#causes">Découvrir nos objectifs <Icon n="fa-solid fa-arrow-right"/></a><a className="btn ghost" href="#advisory">Notre Comité Consultatif</a></div></div><div className="recognition-stamp"><Icon n="fa-solid fa-certificate"/><div><b>RECONNUE OFFICIELLEMENT</b><strong>Récépissé n°001444/RDA/JO6/SAAJP/BAPP</strong><small>27 août 2026 · Préfecture du Mfoundi</small></div></div><div className="slider-controls"><button onClick={()=>setSlide((slide-1+photos.length)%photos.length)} aria-label="Photo précédente"><Icon n="fa-solid fa-arrow-left"/></button><span>{String(slide+1).padStart(2,'0')} / {String(photos.length).padStart(2,'0')}</span><button onClick={()=>setSlide((slide+1)%photos.length)} aria-label="Photo suivante"><Icon n="fa-solid fa-arrow-right"/></button></div></div></section>

   <section className="quick-links"><div className="container quick-grid"><div className="quick-intro"><span className="eyebrow">NOTRE ENGAGEMENT</span><h2>Des actions pensées <span>avec les communautés.</span></h2><p>Une approche territoriale, ouverte à toutes et tous, sans distinction de religion, d’origine ou de statut.</p></div><a href="#donate"><Icon n="fa-solid fa-hand-holding-heart"/><b>Soutenir EVES</b><small>Contribuer aux résultats visés</small></a><a href="#partners"><Icon n="fa-solid fa-people-group"/><b>Devenir partenaire</b><small>Construire avec nous</small></a><a href="#volunteer"><Icon n="fa-solid fa-hands-helping"/><b>Être bénévole</b><small>Donner de son temps</small></a></div></section>

   <section id="about" className="section about"><div className="container two-col"><div><Title e="À PROPOS D’EVES" t="Éducation aux Vulnérabilités de l’Enfance et de la Jeunesse, <span>par l’Économie Sociale et Solidaire.</span>" p="EVES accompagne les enfants, les jeunes et leurs familles les plus vulnérables sur les plans éducatif, social, sanitaire et environnemental."/><p>Notre mission est de contribuer à un environnement où l’éducation, la protection, la santé, la solidarité, l’autonomisation et la résilience deviennent des leviers de développement durable.</p><p>Notre ciblage géographique est prioritairement orienté vers le <strong>Nord-Ouest, l’Extrême-Nord, le Nord, l’Adamaoua, l’Est, l’Ouest et le département du Noun</strong>, avec une ouverture à l’ensemble du territoire national et à l’international selon les besoins.</p><p>La gouvernance doit notamment éclairer la promotion des <strong>Organisations de l’Économie Sociale et Solidaire (OESS)</strong>, tous secteurs confondus : santé, éducation, finance, social, culturel, agricole, etc. Les entreprises publiques à caractère social peuvent également nourrir cette réflexion.</p><div className="official"><Icon n="fa-solid fa-shield-halved"/><div><b>Reconnaissance officielle</b><span>Récépissé de déclaration préfectorale n°001444/RDA/JO6/SAAJP/BAPP du 27 août 2026 — Préfecture du Mfoundi.</span></div></div></div><figure className="editorial-photo"><img src={photos[0].src} alt={photos[0].alt}/><figcaption><b>Grandir. Apprendre. Participer.</b><span>{photos[0].cap}</span></figcaption></figure></div></section>

   <section className="photo-strip"><div className="container"><div className="strip-head"><div><span className="eyebrow">EN IMAGES</span><h2>Des réalités locales, <span>des possibilités.</span></h2></div><p>Éducation, santé, protection, résilience et mobilisation communautaire.</p></div><div className="strip-grid">{photos.slice(1).map(p=><figure key={p.src}><img src={p.src} alt={p.alt}/><figcaption>{p.cap}<small>{p.credit}</small></figcaption></figure>)}</div></div></section>

   <section id="causes" className="section causes"><div className="container"><Title e="NOS 5 OBJECTIFS SPÉCIFIQUES" t="Cinq axes structurent <span>l’action EVES.</span>" p="OS1 Scolarisation · OS2 Résilience climatique · OS3 Protection/VBG · OS4 ESS · OS5 Innovation/plaidoyer."/><div className="axis-grid">{axes.map(([ic,t,d],i)=><article key={t}><span className="axis-number">0{i+1}</span><div className="axis-icon"><Icon n={ic}/></div><h3>{t}</h3><p>{d}</p><a href="#projects">Voir les programmes <Icon n="fa-solid fa-arrow-right"/></a></article>)}</div></div></section>

   <section id="projects" className="section projects"><div className="container"><Title e="PROGRAMMES & RÉSULTATS VISÉS" t="Des objectifs transformés en <span>actions concrètes.</span>"/><div className="project-list">{projects.map(([n,t,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><Icon n="fa-solid fa-arrow-up-right-from-square"/></article>)}</div><div className="target-results"><h3>Résultats ciblés complémentaires</h3><div className="target-grid"><span><Icon n="fa-solid fa-id-card"/> Campagnes d’établissement des actes de naissance</span><span><Icon n="fa-solid fa-comments"/> Causeries éducatives à destination des hommes</span><span><Icon n="fa-solid fa-certificate"/> Certifications courtes aux métiers AGR</span><span><Icon n="fa-solid fa-network-wired"/> Plateforme professionnelle des OESS</span></div></div></div></section>

   <section id="impact" className="impact"><div className="container"><Title e="IMPACT & RESPONSABILITÉ" t="Mesurer les progrès. <span>Rendre compte.</span>" light/><div className="impact-grid">{[['5','objectifs spécifiques','Scolarisation, climat, protection/VBG, ESS, innovation/plaidoyer.'],['7','zones prioritaires','Nord-Ouest, Extrême-Nord, Nord, Adamaoua, Est, Ouest et Noun.'],['6','membres du Bureau Exécutif','Bureau élu par l’Assemblée Générale.'],['2026–2029','cadre stratégique','Business Plan et trajectoire institutionnelle de développement.']].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span><p>{x[2]}</p></div>)}</div><p className="impact-note">Les indicateurs opérationnels seront précisés et actualisés avec les projets effectivement financés et déployés.</p></div></section>

   <section id="team" className="section team"><div className="container"><Title e="GOUVERNANCE" t="Une architecture institutionnelle qui relie <span>terrain, expertise et stratégie.</span>" p="La gouvernance d’EVES est structurée autour de plusieurs instances complémentaires."/><div className="team-grid">{governance.map((g,i)=><article key={g}><Icon n={['fa-solid fa-users-gear','fa-solid fa-flask','fa-solid fa-comments','fa-solid fa-microscope','fa-solid fa-child-reaching'][i]}/><h3>{g}</h3><p>{['Six membres élus par l’Assemblée Générale pour piloter l’association.','Deux co-coordonnateurs dédiés à l’innovation et à la transformation.','Expertise externe et conseils stratégiques pour accompagner les orientations.','Expertise scientifique et recherche appliquée aux problématiques EVES.','Protection et sauvegarde de l’enfant intégrées aux mécanismes institutionnels.'][i]}</p></article>)}</div></div></section>

   <section id="advisory" className="section advisory"><div className="container"><Title e="COMITÉ CONSULTATIF · SEPTEMBRE 2026" t="Des expertises complémentaires pour <span>renforcer EVES.</span>" p="Le Comité Consultatif accompagne la réflexion stratégique, les partenariats, l’expertise sectorielle et les opportunités de développement."/><div className="advisory-grid">{advisory.map(x=><article key={x[1]}><div className="advisory-icon"><Icon n={x[0]}/></div><div><h3>{x[1]}</h3><span className="advisory-role">{x[2]}</span><p>{x[3]}</p></div></article>)}</div><div className="advisory-follow"><div><span className="eyebrow">POINTS DE SUIVI DU COMITÉ</span><h3>Les prochaines décisions et collaborations à cadrer.</h3></div><ul>{followups.map(x=><li key={x}><Icon n="fa-solid fa-circle-check"/>{x}</li>)}</ul></div></div></section>

   <section className="section donation-results"><div className="container"><Title e="RÉSULTATS VISÉS · VOLET DON" t="Donner une réponse concrète aux <span>vulnérabilités.</span>" p="Le volet don vise à structurer une réponse solidaire, transparente et alignée sur les besoins identifiés dans les territoires."/><div className="resource-grid">{donationResults.map(x=><article key={x[1]}><Icon n={x[0]}/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>

   <section id="partners" className="section partners"><div className="container partner-box"><div><span className="eyebrow">PARTENARIATS & FINANCEMENT</span><h2>Des alliances pour <span>changer d’échelle.</span></h2><p>La prospection est engagée auprès notamment de PISCCA, Fondation RAJA, FCLI et UNICEF. Une note de concept a déjà été envoyée à la Fondation RAJA sur le volet OS4.</p></div><a className="btn primary" href="mailto:contact@eves.cm?subject=Partenariat%20EVES">Proposer un partenariat <Icon n="fa-solid fa-arrow-right"/></a></div></section>

   <section id="resources" className="section resources"><div className="container"><Title e="RESSOURCES & DOCUMENTATION" t="Un dossier institutionnel <span>déjà structuré.</span>" p="Les documents publics pourront progressivement être publiés et téléchargés depuis cette bibliothèque."/><div className="resource-grid">{[['fa-solid fa-file-lines','Statuts','Documents constitutifs et cadre institutionnel d’EVES.'],['fa-solid fa-diagram-project','Document Projet v8','Cadre programmatique et logique d’intervention.'],['fa-solid fa-chart-line','Business Plan 2026–2029','Trajectoire stratégique, développement et financement.'],['fa-solid fa-file-circle-check','Note de concept','Documents de conception et de mobilisation des partenaires.'],['fa-solid fa-calendar-days','PTA / Annual Work Plan','Planification annuelle des activités et priorités.'],['fa-solid fa-chart-simple','Cadre M&E','Suivi, évaluation, apprentissage et redevabilité.']].map(x=><article key={x[1]}><Icon n={x[0]}/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>

   <section id="news" className="section news"><div className="container"><Title e="ACTUALITÉS & BLOG" t="Les nouvelles de <span>notre réseau.</span>"/><div className="news-grid">{news.map(x=><article key={x[1]}><span className="tag">{x[0]}</span><small>{x[2]}</small><h3>{x[1]}</h3><p>{x[3]}</p><a href="#contact">Lire l’article <Icon n="fa-solid fa-arrow-right"/></a></article>)}</div></div></section>

   <section id="events" className="section events"><div className="container"><Title e="ÉVÉNEMENTS & JALONS" t="Une trajectoire qui se construit <span>dans le temps.</span>"/><div className="event-list">{events.map(x=><article key={x[0]}><Icon n="fa-regular fa-calendar-days"/><strong>{x[0]}</strong><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></div></section>

   <section id="volunteer" className="volunteer"><div className="container volunteer-box"><div><span className="eyebrow gold">DEVENIR BÉNÉVOLE</span><h2>Votre temps peut devenir <span>une force.</span></h2><p>Participez aux actions communautaires, à la communication, à la recherche, aux événements, au renforcement des capacités ou à la mobilisation du réseau.</p></div><a className="btn light-btn" href="mailto:contact@eves.cm?subject=Volontariat%20EVES">Je veux m’engager <Icon n="fa-solid fa-arrow-right"/></a></div></section>

   <section id="donate" className="section donate"><div className="container donate-box"><div><span className="eyebrow">SOUTENIR EVES</span><h2>Chaque contribution peut <span>ouvrir une possibilité.</span></h2><p>Soutenez les programmes de scolarisation, protection, santé, climat, ESS, SAFEHOME / Maison des Résiliences, renforcement des capacités et accès à l’eau.</p></div><div className="donate-actions"><a className="btn primary" href="mailto:contact@eves.cm?subject=Soutien%20EVES"><Icon n="fa-solid fa-heart"/> Soutenir le programme</a><a className="btn outline-dark" href="#contact">Nous contacter</a></div></div></section>

   <section className="newsletter"><div className="container newsletter-box"><div><span className="eyebrow">NEWSLETTER EVES</span><h2>Recevez les nouvelles <span>du réseau.</span></h2><p>Actualités, appels à collaboration, événements, opportunités de financement et informations sur les actions EVES.</p></div><form onSubmit={e=>e.preventDefault()}><label htmlFor="email">Votre adresse email</label><div><input id="email" type="email" placeholder="vous@exemple.com" required/><button className="btn primary">S’abonner <Icon n="fa-solid fa-paper-plane"/></button></div><small>En vous inscrivant, vous acceptez de recevoir les communications d’EVES.</small></form></div></section>

   <section id="contact" className="section contact"><div className="container contact-grid"><div><Title e="CONTACT" t="Parlons de ce que nous pouvons <span>construire ensemble.</span>"/><p>Pour un partenariat, une proposition de projet, une demande d’information, une implication bénévole, un don ou une collaboration avec une OESS, contactez EVES.</p><div className="contact-links"><a href="mailto:contact@eves.cm"><Icon n="fa-solid fa-envelope"/> contact@eves.cm</a><a href="tel:+237656987759"><Icon n="fa-solid fa-phone"/> +237 656 987 759</a><a href="#home"><Icon n="fa-solid fa-globe-africa"/> Cameroun · National · International selon les besoins</a></div></div><div className="contact-card"><img src="/logo.svg" alt="Logo officiel EVES"/><b>Éducation · Protection · Émancipation</b><span>Association camerounaise engagée auprès des enfants, des jeunes et des familles vulnérables.</span><div className="zones">{zones.map(z=><span key={z}>{z}</span>)}</div></div></div></section>
  </main>
  <footer><div className="container footer-grid"><div><img className="footer-logo" src="/logo.svg" alt="Logo EVES"/><p>EVES agit pour la scolarisation, la protection, la santé, la résilience climatique, l’économie sociale et solidaire, l’innovation et le plaidoyer.</p></div><div><b>Navigation</b><a href="#about">À propos</a><a href="#causes">5 objectifs</a><a href="#projects">Programmes</a><a href="#advisory">Comité consultatif</a><a href="#news">Actualités</a><a href="#contact">Contact</a></div><div><b>Nous rejoindre</b><a href="#volunteer">Bénévolat</a><a href="#partners">Partenariat</a><a href="#donate">Soutenir EVES</a><a href="#resources">Ressources</a></div></div><div className="container footer-bottom"><span>© 2026 EVES — Tous droits réservés.</span><span>Développé par <b>MTECHsolutions</b> · +237 656 987 759</span></div></footer>
 </div>
}
export default App
