import { useState } from 'react'
import { Menu, X, ArrowRight, BookOpen, ShieldCheck, HeartPulse, Leaf, Megaphone, Users, HandHeart, Newspaper, CalendarDays, FileText, Mail, MapPin } from 'lucide-react'

const causes=[
{icon:BookOpen,title:'Éducation',text:'Favoriser l’accès, le maintien et la réinsertion scolaire des enfants et des jeunes vulnérables.',target:'Éducation inclusive'},
{icon:ShieldCheck,title:'Protection & autonomisation',text:'Prévenir les violences, renforcer la protection et créer des parcours d’autonomie pour les jeunes.',target:'Protection intégrée'},
{icon:HeartPulse,title:'Santé',text:'Promouvoir le bien-être, l’orientation et l’accès aux ressources sanitaires pour les communautés vulnérables.',target:'Bien-être & santé'},
{icon:Leaf,title:'Résilience climatique',text:'Soutenir les pratiques communautaires durables, la sensibilisation environnementale et l’adaptation climatique.',target:'Communautés résilientes'},
{icon:Megaphone,title:'Mobilisation & plaidoyer',text:'Fédérer les acteurs, documenter les expériences et porter les voix des communautés auprès des décideurs.',target:'Influence collective'}]
const projects=[
['01','Programme éducation & réinsertion','Accompagnement des enfants et jeunes vulnérables à travers les associations et réseaux locaux.'],
['02','Protection de l’enfance et jeunesse','Prévention, orientation, accompagnement psychosocial et renforcement des mécanismes communautaires.'],
['03','Initiatives santé communautaire','Mobilisation des acteurs sociaux et solidaires autour de la santé et du bien-être.'],
['04','Résilience & économie sociale et solidaire','Appui aux OESS comme leviers de développement durable et d’autonomisation.'],
['05','Laboratoire, recherche & plaidoyer','Recherche-action, mentorat, capitalisation et mobilisation pour des politiques plus inclusives.']]
const stats=[['400+','enfants & jeunes','maintenus ou réinsérés dans l’éducation'],['1 500','familles','ciblées par les actions de sensibilisation'],['15','associations relais','à renforcer et mobiliser'],['7','zones prioritaires','avec une ouverture au territoire national']]
const news=[
['Actualité','EVES officiellement reconnue','27 août 2026','EVES est officiellement reconnue par récépissé de déclaration préfectorale n°001444/RDA/JO6/SAAJP/BAPP du 27 août 2026, Préfecture du Mfoundi.'],
['Réseau','Construire une communauté d’action','2026','Membres, référents régionaux, partenaires et associations relais sont appelés à coordonner les actions et opportunités de collaboration.'],
['Vision','L’ESS au cœur du développement territorial','2026','EVES place les organisations de l’économie sociale et solidaire au centre d’une approche communautaire, inclusive et durable.']]
const events=[['2026','Lancement institutionnel','Présentation du réseau EVES, de ses axes et de ses zones d’intervention.'],['2027','Déploiement pilote','Mise en œuvre progressive des programmes et mobilisation des associations relais.'],['2028–2029','Capitalisation & expansion','Documentation des résultats, partenariats et extension selon les besoins et financements.']]
function Logo({compact=false}){return <div className={`logo ${compact?'logo-compact':''}`}><img src="/logo.svg" alt="EVES"/>{!compact&&<span>Éducation • Protection • Émancipation</span>}</div>}
function SectionTitle({kicker,title,text}){return <div className="section-heading"><div className="kicker">{kicker}</div><h2 dangerouslySetInnerHTML={{__html:title}}/>{text&&<p>{text}</p>}</div>}
function App(){
const [menu,setMenu]=useState(false);const close=()=>setMenu(false)
const nav=[['home','Accueil'],['about','À propos'],['causes','Causes'],['projects','Projets'],['impact','Impact'],['team','Équipe'],['partners','Partenaires'],['resources','Ressources'],['news','Actualités'],['events','Événements'],['volunteer','Bénévolat'],['donate','Soutenir'],['contact','Contact']]
return <div className="site">
<div className="topbar"><div className="container topbar-inner"><span><b>EVES</b> — Association camerounaise</span><span><a href="tel:+237656987759">MTECHsolutions : +237 656 987 759</a><span className="dot">•</span><a href="mailto:contact@eves.cm">contact@eves.cm</a></span></div></div>
<header className="header"><div className="container header-inner"><a href="#home" onClick={close}><Logo/></a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}>{nav.map(([id,label])=><a key={id} href={`#${id}`} onClick={close}>{label}</a>)}<a className="donate-btn" href="#donate" onClick={close}>SOUTENIR EVES</a></nav></div></header>
<main>
<section id="home" className="hero"><div className="hero-shade"/><div className="container hero-content"><div className="hero-copy"><div className="kicker light">ÉDUCATION • PROTECTION • ÉMANCIPATION</div><h1>Ensemble, construisons un avenir <em>plus inclusif.</em></h1><p>EVES accompagne les enfants, les jeunes et leurs familles les plus vulnérables sur les plans éducatif, social, sanitaire et environnemental, en s’appuyant sur les organisations de l’économie sociale et solidaire.</p><div className="hero-actions"><a className="btn btn-primary" href="#causes">Découvrir nos actions <ArrowRight size={17}/></a><a className="btn btn-outline" href="#about">Qui sommes-nous ?</a></div></div><div className="hero-badge"><b>RECONNUE OFFICIELLEMENT</b><span>Récépissé préfectoral n°001444/RDA/JO6/SAAJP/BAPP</span><small>27 août 2026 · Préfecture du Mfoundi</small></div></div></section>
<section className="intro"><div className="container intro-grid"><div><div className="kicker">NOTRE ENGAGEMENT</div><h2>Un soutien chaleureux et véritable <span>pour les personnes qui en ont besoin.</span></h2><p>Notre action part des communautés, valorise leurs forces et renforce les solidarités existantes.</p></div><div className="intro-cards"><a href="#donate"><HandHeart/><b>Soutenir EVES</b><small>Contribuer à nos actions</small></a><a href="#partners"><Users/><b>Devenir partenaire</b><small>Construire avec nous</small></a><a href="#volunteer"><HeartPulse/><b>Devenir bénévole</b><small>Donner de son temps</small></a></div></div></section>
<section id="about" className="section about"><div className="container two-col"><div><SectionTitle kicker="À PROPOS D’EVES" title="Une société où chaque enfant peut <span>réaliser son potentiel.</span>"/><p>EVES — <strong>Éducation aux Vulnérabilités de l’Enfance et de la Jeunesse, par l’Économie Sociale et Solidaire</strong> — est une organisation camerounaise engagée auprès des enfants, des jeunes et de leurs familles les plus vulnérables.</p><p>Nous intervenons sans distinction de religion, d’origine ou de statut et développons une approche fondée sur la solidarité, l’inclusion, l’autonomisation et la coopération.</p><div className="recognition"><ShieldCheck/><div><b>Reconnaissance officielle</b><span>Récépissé n°001444/RDA/JO6/SAAJP/BAPP du 27 août 2026 — Préfecture du Mfoundi.</span></div></div></div><div className="about-card"><div className="about-emblem"><Logo compact/><strong>EVES</strong><span>Économie Sociale<br/>et Solidaire</span></div></div></div></section>
<section id="causes" className="section causes"><div className="container"><SectionTitle kicker="NOS 5 AXES" title="Les causes qui <span>nous mobilisent.</span>" text="Cinq axes structurent l’action d’EVES et relient les besoins du terrain à la mobilisation, au partenariat et au plaidoyer."/><div className="cards five">{causes.map(({icon:Icon,title,text,target},i)=><article className="cause-card" key={title}><div className="card-top"><div className="icon"><Icon size={23}/></div><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p><b>{target}</b></article>)}</div></div></section>
<section id="projects" className="section projects"><div className="container"><SectionTitle kicker="NOS PROJETS" title="Des programmes conçus pour <span>agir concrètement.</span>"/><div className="project-list">{projects.map(([n,t,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowRight size={20}/></article>)}</div></div></section>
<section id="impact" className="impact section"><div className="container"><SectionTitle kicker="IMPACT & RESPONSABILITÉ" title="Des objectifs mesurables.<br/><span>Une responsabilité partagée.</span>"/><div className="stats">{stats.map(([n,t,d])=><div key={t}><strong>{n}</strong><b>{t}</b><p>{d}</p></div>)}</div><p className="note">Les indicateurs présentés correspondent aux ambitions et cibles de développement d’EVES et évolueront avec les projets effectivement financés et déployés.</p></div></section>
<section id="team" className="section team"><div className="container"><SectionTitle kicker="NOTRE ÉQUIPE" title="Des femmes et des hommes engagés <span>au service des communautés.</span>" text="Une gouvernance et des équipes appelées à travailler avec les référents régionaux, associations relais, partenaires et communautés."/><div className="team-grid"><article><div className="avatar">EV</div><h3>Direction & coordination</h3><p>Pilotage stratégique, coordination des programmes et relations institutionnelles.</p></article><article><div className="avatar">CO</div><h3>Coordination régionale</h3><p>Référents et relais territoriaux pour la mise en œuvre des actions sur le terrain.</p></article><article><div className="avatar">ES</div><h3>Réseau des OESS</h3><p>Associations et organisations de l’économie sociale et solidaire partenaires d’EVES.</p></article></div></div></section>
<section id="partners" className="section partners"><div className="container partner-panel"><div><div className="kicker">PARTENARIATS</div><h2>Construisons ensemble des <span>solutions durables.</span></h2><p>EVES est ouverte aux collaborations avec associations, institutions, collectivités, universités, entreprises, bailleurs, fondations et acteurs de l’ESS.</p></div><a className="btn btn-primary" href="mailto:contact@eves.cm?subject=Partenariat%20EVES">Proposer un partenariat <ArrowRight size={17}/></a></div></section>
<section id="resources" className="section resources"><div className="container"><SectionTitle kicker="RESSOURCES & RAPPORTS" title="Comprendre, documenter et <span>partager l’impact.</span>"/><div className="resource-grid"><article><FileText/><b>Rapports & publications</b><p>Rapports d’activités, notes, études et documents de capitalisation.</p><a href="#contact">Bientôt disponibles <ArrowRight size={15}/></a></article><article><Newspaper/><b>Bibliothèque EVES</b><p>Ressources sur l’éducation, la protection, la santé, le climat et l’ESS.</p><a href="#contact">Explorer les ressources <ArrowRight size={15}/></a></article><article><MapPin/><b>Zones d’intervention</b><p>Nord-Ouest, Extrême-Nord, Nord, Adamaoua, Est, Ouest et Noun.</p><a href="#contact">Voir notre couverture <ArrowRight size={15}/></a></article></div></div></section>
<section id="news" className="section news"><div className="container"><SectionTitle kicker="ACTUALITÉS & BLOG" title="Les nouvelles de <span>notre réseau.</span>"/><div className="news-grid">{news.map(([tag,title,date,text])=><article key={title}><span className="tag">{tag}</span><small>{date}</small><h3>{title}</h3><p>{text}</p><a href="#contact">Lire l’article <ArrowRight size={15}/></a></article>)}</div></div></section>
<section id="events" className="section events"><div className="container"><SectionTitle kicker="ÉVÉNEMENTS" title="Agir ensemble, <span>sur le terrain.</span>"/><div className="event-list">{events.map(([date,title,text])=><article key={date}><CalendarDays/><strong>{date}</strong><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
<section id="volunteer" className="volunteer section"><div className="container volunteer-inner"><div><div className="kicker light">DEVENIR BÉNÉVOLE</div><h2>Votre temps peut devenir <span>une force.</span></h2><p>Rejoignez le réseau EVES pour soutenir les actions communautaires, la communication, la recherche, l’animation, le mentorat ou la mobilisation.</p></div><a className="btn btn-white" href="mailto:contact@eves.cm?subject=Volontariat%20EVES">Je veux m’engager <ArrowRight size={17}/></a></div></section>
<section id="donate" className="section donate"><div className="container donate-box"><div><div className="kicker">SOUTENIR EVES</div><h2>Chaque contribution peut ouvrir <span>une nouvelle possibilité.</span></h2><p>Votre soutien aide à renforcer les capacités locales et à développer des actions au bénéfice des enfants, des jeunes et des familles vulnérables.</p></div><a className="btn btn-primary" href="mailto:contact@eves.cm?subject=Soutenir%20EVES">Faire une demande de soutien <ArrowRight size={17}/></a></div></section>
<section className="newsletter"><div className="container newsletter-inner"><div><div className="kicker">NEWSLETTER EVES</div><h2>Recevez les nouvelles de <span>notre réseau.</span></h2><p>Actualités, opportunités de collaboration, événements et publications directement dans votre boîte mail.</p></div><form onSubmit={e=>e.preventDefault()}><input type="email" aria-label="Votre adresse email" placeholder="Votre adresse email" required/><button className="btn btn-primary" type="submit">S’inscrire <ArrowRight size={16}/></button><small>En vous inscrivant, vous acceptez de recevoir les communications d’EVES.</small></form></div></section>
<section id="contact" className="section contact"><div className="container"><SectionTitle kicker="CONTACT" title="Parlons de la <span>prochaine action.</span>"/><div className="contact-grid"><div><a href="mailto:contact@eves.cm"><Mail/>contact@eves.cm</a><a href="tel:+237656987759"><MapPin/>+237 656 987 759 — MTECHsolutions, développement web</a><div><b>Zones prioritaires</b><p>Nord-Ouest · Extrême-Nord · Nord · Adamaoua · Est · Ouest · Noun · et, selon les besoins, l’ensemble du territoire et l’international.</p></div></div><div className="contact-card"><Logo/><p>Éducation aux Vulnérabilités de l’Enfance et de la Jeunesse, par l’Économie Sociale et Solidaire.</p><b>Développé par MTECHsolutions</b><span>Tel. +237 656 987 759</span></div></div></div></section>
</main>
<footer><div className="container footer-grid"><div><Logo/><p>Une organisation camerounaise au service de l’éducation, de la protection, de la santé, de la résilience climatique et de la mobilisation.</p></div><div><b>Navigation</b><a href="#about">À propos</a><a href="#projects">Projets</a><a href="#impact">Impact</a><a href="#news">Blog & actualités</a></div><div><b>Engagement</b><a href="#volunteer">Bénévolat</a><a href="#partners">Partenaires</a><a href="#donate">Soutenir</a><a href="#contact">Contact</a></div></div><div className="container footer-bottom"><span>© 2026 EVES — Tous droits réservés.</span><span>Développé par <b>MTECHsolutions</b> · +237 656 987 759</span></div></footer>
</div>}
export default App
